### ISSUE TITLE
co2meter.com's RAD-0301 requires additional data decoding

### ISSUE THREAD

**Issue by zeldovich** [patrislav1/zytemp_mqtt#1]
When using zytempmqtt with a RAD-0301 from co2meter.com, I get:

```% /usr/bin/python3 -m zytempmqtt --debug
INFO:zytemp:Found CO2 sensor at intf. 0, 0001:0006:00, VID=04d9, PID=a052
INFO:zytemp:Using device at 0001:0006:00
INFO:mqtt:connected to ...
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
DEBUG:zytemp:Unexpected data from device
```

However, when I add the "decryption" support from https://github.com/vfilimonov/co2meter/blob/master/co2meter/co2meter.py#L197 (and the initialization at https://github.com/vfilimonov/co2meter/blob/master/co2meter/co2meter.py#L147), I get data that parses correctly.

I haven't tried to understand the protocol for this device, which is why I'm submitting this as an issue rather than a PR..  I also don't know why my RAD-0301 seems to require this additional step, even though zytempmqtt's README.md has a link to seemingly the same model (RAD-0301) on co2meter.com's site as a supported device.  Maybe my RAD-0301 is an older version?

**Comment by patrislav1** [comment]
I only have a TFA Dostmann unit which sends unencrypted data, so if I added the decryption support I couldn't test it :-/

**Comment by zeldovich** [comment]
Fair enough; thanks!

Since I have no idea how to determine which devices need decryption and which devices don't need it, it's probably best for me to just keep a separate fork with decryption support.

**Comment by patrislav1** [comment]
If you run a fork with support for that device anyway, we could merge it and see if it works for both kinds of devices? WDYT?

**Comment by zeldovich** [comment]
Sure, filed as PR #3

**Comment by patrislav1** [comment]
Merged, thank you.
